language: node_js
node_js:
- '5'
addons:
  code_climate:
    repo_token: 9a24182f43196f072142477a6bb4862781c38ba73f14f54e1d410554fd49bc51
before_script:
- npm install -g codeclimate-test-reporter
after_script:
- codeclimate-test-reporter < coverage/lcov.info
